name: Docker Build and Wiz Scan

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        echo "Building Docker image with tag: vuln_django_app:${{ github.sha }}"
        docker build -t vuln_django_app:${{ github.sha }} .
        echo "Docker image built successfully"
        
    - name: Download and install Wiz CLI
      run: |
        echo "Downloading Wiz CLI..."
        # Download wizcli for Linux x64
        curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64
        chmod +x wizcli
        sudo mv wizcli /usr/local/bin/
        echo "Wiz CLI installed successfully"
        wizcli version
        
    - name: Authenticate to Wiz
      run: |
        export WIZ_ENV=fedramp
        wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}
      shell: bash
        
    - name: Scan Docker image with Wiz
      run: |
        echo "Starting Wiz scan of Docker image: vuln_django_app:${{ github.sha }}"
        echo "Using Wiz FedRamp environment (WIZ_ENV=fedramp)"
        # Scan the built Docker image
        wizcli docker scan --image vuln_django_app:${{ github.sha }}
