name: Docker Build and Wiz Scan

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t vuln_django_app:${{ github.sha }} .
        
    - name: Download and install Wiz CLI
      run: |
        # Download wizcli for Linux x64
        curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64
        chmod +x wizcli
        sudo mv wizcli /usr/local/bin/
        
    - name: Scan Docker image with Wiz
      env:
        WIZ_ENV: fedramp
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: |
        # Scan the built Docker image
        wizcli docker scan --image vuln_django_app:${{ github.sha }}